In [1]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [2]:
import numpy as np
import pandas as pd

In [3]:
import sys
sys.path.insert(0,"/gdrive/Shareddrives/FYP Project/Notebooks/helper_modules")

In [4]:
df = pd.read_csv("/gdrive/Shareddrives/FYP Project/Dataset/FoodData_modified.csv")

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [6]:
from Utils import preprocess_dataset

In [7]:
data = preprocess_dataset(df)

In [8]:
data[3]

['Calories (kcal)',
 'Protein (g)',
 'Fats (g)',
 'Carbs (g)',
 'Fiber (g)',
 'Sugar (g)',
 'Phosphorus (mg)',
 'Potassium (mg)',
 'Sodium (mg)',
 'Saturated Fat (g)',
 'Trans Fat (g)']

In [9]:
X=data[0][["Calories (kcal)",'Protein (g)', 'Carbs (g)', 'Fats (g)']].values

In [10]:
X

array([[3.130e+02, 1.296e+01, 5.577e+01, 4.270e+00],
       [3.530e+02, 7.000e+00, 4.460e+01, 1.630e+01],
       [2.720e+02, 1.075e+01, 5.188e+01, 2.420e+00],
       ...,
       [2.200e+01, 1.140e+00, 3.810e+00, 7.200e-01],
       [1.200e+01, 1.100e+00, 2.230e+00, 1.700e-01],
       [2.840e+02, 9.250e+00, 7.301e+01, 7.300e-01]])

In [11]:
Y=data[2]

In [12]:
x_train, x_test, y_train, y_test = train_test_split( X, Y, test_size=0.33, random_state=42)

In [13]:
clf =  RandomForestClassifier(n_estimators = 100, max_depth = 29, max_features = 4, max_samples = 1.0, random_state=0)
clf.fit(x_train, y_train)

RandomForestClassifier(max_depth=29, max_features=4, max_samples=1.0,
                       random_state=0)

In [14]:
clf.score(x_test, y_test)

0.7582417582417582

In [15]:
clf.predict(np.array([400, 0, 99.6, 0]).reshape(1,-1))

array([1])

In [16]:
history = {"clf": clf.score(x_test, y_test)}

In [30]:
pipeline = Pipeline(steps=[("imputer", SimpleImputer(strategy="constant")),("model", RandomForestClassifier(n_estimators = 100, max_depth = 29, max_features = 4, max_samples = 1.0, random_state=0)) ])

In [31]:
pipeline.fit(x_train, y_train)

Pipeline(steps=[('imputer', SimpleImputer(strategy='constant')),
                ('model',
                 RandomForestClassifier(max_depth=29, max_features=4,
                                        max_samples=1.0, random_state=0))])

In [32]:
pipeline.score(x_test, y_test)

0.7582417582417582

In [25]:
pipeline.predict(np.array([77, 2, 17, 0.1]).reshape(1,-1))

array([0])